# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Careem-Test-Imdb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Careem-Test-Imdb
  pod 'Kingfisher', '~> 5.0'
  target 'Careem-Test-ImdbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Careem-Test-ImdbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
